version: '3'
services:
    nlsubs-service:
        image: registry.domain.com/project_name/nl_msa_database:0.0.1
        restart: always
        networks:
            - workbench 
        restart: always
        ports:
            - "8081:8081"
networks:
  workbench:
    external: true
